<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pdx</string>
	</array>
	<key>name</key>
	<string>PDX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;[!%]--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.xml.ant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--%?&gt;</string>
			<key>name</key>
			<string>comment.block.xml.ant</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pdx</string>
	<key>uuid</key>
	<string>992e6270-3764-11e6-bdf4-0800200c9a66</string>
</dict>
</plist>